# ブロックタイプ定義ファイル
# このファイルでカスタムブロックタイプを定義できます
# 注意: 「dialogue（セリフ）」と「narrative（地の文）」は標準定義として常に含まれます

block_types:
    
  command:
    label: "コマンド"
    description: "シナリオスクリプトの演出効果"
    requires_text: false
    parameters:
      commandType:
        type: "select"
        label: "コマンドタイプ"
        default: "screen"
        required: true
        options:
          - value: "screen"
            label: "画面演出"
          - value: "sound"
            label: "音響効果"
          - value: "transition"
            label: "画面転換"
          - value: "wait"
            label: "待機"
          - value: "system"
            label: "システム"
          - value: "custom"
            label: "カスタム"
      effect:
        type: "select"
        label: "効果"
        default: "shake"
        required: true
        options:
          - value: "shake"
            label: "画面揺れ"
          - value: "flash"
            label: "フラッシュ"
          - value: "fade"
            label: "フェード"
          - value: "zoom"
            label: "ズーム"
          - value: "blur"
            label: "ブラー"
          - value: "none"
            label: "なし"
      intensity:
        type: "select"
        label: "強度"
        default: "normal"
        required: true
        options:
          - value: "weak"
            label: "弱"
          - value: "normal"
            label: "中"
          - value: "strong"
            label: "強"
      duration:
        type: "number"
        label: "継続時間"
        placeholder: "秒数"
        default: 1.0
        required: true
        min: 0
        step: 0.1